Update build-libwrt-jdc-arthur.yml

diff --git a/.github/workflows/build-libwrt-jdc-arthur.yml b/.github/workflows/build-libwrt-jdc-arthur.yml
--- a/.github/workflows/build-libwrt-jdc-arthur.yml
+++ b/.github/workflows/build-libwrt-jdc-arthur.yml
@@ -29,14 +29,25 @@ jobs:
           sudo systemctl stop apache2 || true
           sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
 
-      - name: Clone LibWrt source
+            - name: Clone LibWrt source
         run: |
-          git clone --depth 1 -b main-nss https://github.com/LiBwrt/openwrt-6.x.git openwrt
+          for i in {1..3}; do
+            git clone --depth 1 -b main-nss https://github.com/LiBwrt/openwrt-6.x.git openwrt && break
+            echo "Clone failed, retrying in 5 seconds..."
+            sleep 5
+          done
+
+          if [ ! -d "openwrt" ]; then
+            echo "Clone failed after 3 attempts."
+            exit 1
+          fi
+
           cd openwrt
           if [ -n "${{ github.event.inputs.repo_commit }}" ]; then
             git fetch origin ${{ github.event.inputs.repo_commit }}
             git checkout ${{ github.event.inputs.repo_commit }}
           fi
+
 
       - name: Copy .config
         run: |
